# Shib SP configuration for CI testing.
# Profile: gv.at PVP 2.1

httpd:
    hostname: sp.testdom.test

Metadata:
    entity_category: http://www.ref.gv.at/ns/names/agiz/pvp/egovtoken
    xml_lang: en
    mdui_DisplayName: Shibboleth SP Test
    mdui_Description: Shibboleth SP Echo Service (Test)
    mdui_Logo: https://sp.testdom.test/logo.png
    wantsAuthnRequestSigned: yes
    ContactPerson_support_Givenname: Franz
    ContactPerson_support_Surname: Meier
    ContactPerson_support_Email: fxmeier@testdom.test
    ContactPerson_technical_Givenname: Franz
    ContactPerson_technical_Surname: Meier
    ContactPerson_technical_Email: fxmeier@testdom.test
    OrganizationName: CI-Test
    OrganizationDisplayName: Continuous Integration Testing
    OrganizationUrl: https://www.testdom.test

Shibboleth2:
    entityID: https://sp.testdom.test/sp
    REMOTE_USER: X-PVP-BPK X-PVP-GID X-PVP-USERID persistent-id targeted-id
    ApplicationDefaults_signing: "true"
    SSO_discoveryURL: https://idpdisco.testdom.test/role/idp.ds
    Errors_supportContact: admin@testdom.test
    MetadataProvider_url: https://mdfeed.testdom.test/metadata.xml
    # select a profile that will copy files (such as attribute-map and -policy) to /etc/shibboleth
    Profile: default
