Common
    entityID: https://sp.example.org/sp
    hostname: sp.example.org

Metadata
    entity-category: http://www.ref.gv.at/ns/names/agiz/pvp/egovtoken
    xml_lang: en
    mdui_DisplayName: BKA Mitarbeiter (Test, extern)
    mdui_Description: BKA Mitarbeiter Stammportal (Test, extern)
    mdui_Logo: https://fairchat.net/rcstatic/img/rot-weiss-rot-logo300x100px.png
    wantsAuthnRequestSigned: yes
    ContactPerson_support_Givenname: Franz
    ContactPerson_support_Surname: Meier
    ContactPerson_support_Email: fxmeier@bka.gv.at
    ContactPerson_technical_Givenname: Franz
    ContactPerson_technical_Surname: Meier
    ContactPerson_technical_Email: fxmeier@bka.gv.at
    OrganizationName: BKA
    OrganizationDisplayName: Bundeskanzleramt
    OrganizationUrl: https://www.bka.gv.at

Shibboleth2
    ApplicationDefaults.REMOTE_USER: persistent-id targeted-id uid X-PVP-USERID X-PVP-GID X-PVP-BPK 
    ApplicationDefaults.signing: true
    Sessions.SSO: discoveryProtocol="SAMLDS" discoveryURL="https://disco.test.portalverbund.gv.at/role/idp.ds"
    MetadataProvider type="XML" validate="true" file="/opt/md_feed/metadata.xml"